language: csharp
mono: 
 - latest
dotnet: 2.0.0
matrix:
  include:
    - os: linux
      dist: trusty      
      sudo: required
    - os: osx
      osx_image: xcode9      
      sudo: required               
script:  
  - sudo nuget update -self
  - dotnet build travistest.csproj