language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode9      
      sudo: required          
before_install:
  - brew update
install:
  - ulimit -n4096  
  - brew install dotnet-sdk
script:  
  - dotnet buils travistest.csproj